django-examples/forms.py
# --*-- encoding: utf-8 --*--

from django import forms


class PaymentForm(forms.Form):
    
    # NOTE: cross_key must be handled at the server-side only.

    allat_shop_id = forms.SlugField(max_length=20, widget=forms.HiddenInput())      # Initialized as settings.PAYMENT_SHOPID.
    allat_order_no = forms.CharField(max_length=70, label=u'Order ID',              # Automatically generated per order.
                                     widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    allat_amt = forms.IntegerField(label=u'Amount', min_value=0,                    # NOTE: must be validated at the server-side
                                   widget=forms.HiddenInput())
    allat_pmember_id = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'readonly': 'readonly'}), label=u'User ID')
    allat_product_cd = forms.CharField(max_length=1000, widget=forms.HiddenInput()) # Should be initialized from order information.
    allat_product_nm = forms.CharField(max_length=1000, widget=forms.HiddenInput()) # Should be initialized from order information.
    allat_buyer_nm = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    allat_recp_nm = forms.CharField(max_length=20, widget=forms.HiddenInput())      # Should be initialized from order information.
    allat_recp_addr = forms.CharField(max_length=120, widget=forms.HiddenInput())   # Should be initialized from order information.

    allat_enc_data = forms.CharField(max_length=8192, widget=forms.HiddenInput())   # Automatically set by the frontend plugin.
                                                                                    # Unfortunately, the official documentation
                                                                                    # does not specify the max length of this field.
                                                                                    # 8 KB seems to be enough, but tests are required
                                                                                    # when people buys multiple products.

    allat_company_nm = forms.CharField(max_length=20, widget=forms.HiddenInput())   # Uses internal value.
    allat_company_url = forms.CharField(max_length=50, widget=forms.HiddenInput())  # Uses internal value.
    allat_test_yn = forms.CharField(max_length=1, widget=forms.HiddenInput())       # Depending on DEBUG mode.


class PaymentCancelForm(forms.Form):
    allat_shop_id = forms.SlugField(max_length=20, widget=forms.HiddenInput())
    allat_order_no = forms.CharField(max_length=70, label=u'Order ID', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    # TODO: display amount?
    allat_amt = forms.CharField(max_length=10, widget=forms.HiddenInput())
    allat_pay_type = forms.CharField(max_length=6, widget=forms.HiddenInput(), initial=u'CARD')  # This example is for credit cards only.

    allat_enc_data = forms.CharField(max_length=8192, widget=forms.HiddenInput())
    allat_opt_pin = forms.CharField(max_length=100, widget=forms.HiddenInput(), initial=u'NOVIEW')
    allat_opt_mod = forms.CharField(max_length=100, widget=forms.HiddenInput(), initial=u'WEB')

django-examples/templates/layout.html
<!doctype HTML>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{{ STATIC_URL }}common.css">
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
{% block extra_header %}
{% endblock %}
</head>
<body>
<div id="wrap">
	<div id="header">
		<h1>Website Title</h1>
		{# include "navigation.html" #}
	</div>
	<div id="content">
	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	{% block content %}{% endblock %}
	</div>
	<div id="footer">
	{% block extra_footer %}{% endblock %}
	</div>
</div>
</body>
</html>

django-examples/templates/payment_form.html
{% extends "layout.html" %}
{# 사실 제대로 하려면 allatpay 관련 스크립트도 PaymentForm에 종속적인 것이므로 그쪽의 static resource로 제공해야 함. 일단 귀찮아서 패스. #}
{% block extra_header %}
<script type="text/javascript" charset="euc-kr" src="https://tx.allatpay.com/common/AllatPay{% if region == "DOMESTIC" %}RE{% else %}EN{% endif %}.js"></script>
<script type="text/javascript">
function ftn_approval(dfm) {
	var ret = visible_Approval(dfm);
	var code = ret.substring(0,4);
	if (code != "0000" && code != "9999") { // Arghhh... we have errors.
		alert('An error occurred! If it seems a temporary one, please try again later. Otherwise, please report the following error information:\n\n' + ret);
		return;
	}
	if (code == "9999") { // Payment process is cancelled by the user.
		alert('You have cancelled the payment.');
		return;
	}

	alert('Payment is successful! Please check your receipt on a pop-up window. If an empty screen shows up, try refreshing it.')
	var urls ="http://www.allatpay.com/servlet/AllatBizPop/member/pop_card_receipt.jsp?shop_id={{shop_id}}&order_no={{order_no}}";
	window.open(urls,"app","width=410,height=650,scrollbars=0");
}
</script>
{% endblock %}
{% block title %}Payment Form{% endblock %}
{% block content %}
<h2>Registration ({% if registration_type == "earlybird" %}Early bird{% else %}Standard, with full rates{% endif %})</h2>
<noscript>
<p class="warning">This page requires Javascript to be enabled!</p>
</noscript>
<form id="payment-form" action="/registration/step2/" method="POST">
{% csrf_token %}
<input type="hidden" name="step" value="2">
<table class="form" style="width: 95%">
{{ payment_form.as_table }}
<tr><th>Amount:</th><td><span id="amount-display"></span></td></tr>
<tr class="submit-row"><th>&nbsp;</th><td><input type="submit" name="submit_action" value="Confirm to pay" id="payment-form-submit"></td></tr>
</table>
</form>
<script type="text/javascript">
var region = '{{ region }}';
$('#payment-form-submit').click(function() {
	ftn_approval($('#payment-form').get(0));
	return false;
});
$(document).ready(function() {
	if (region == 'DOMESTIC') {
		$('#amount-display').text('₩ ' + $('#id_allat_amt').val());
	} else {
		var x = parseInt($('#id_allat_amt').val());
		$('#amount-display').text('$ ' + (x / 100).toFixed(2)); // The unit of USD is cents, not dollars.
	}
});
</script>
{% endblock %}

django-examples/templates/transaction_result.html
{% extends "layout.html" %}
{% block title %}Result{% endblock %}
{% block content %}
{% if success %}
<p>Your request has been successfully processed!</p>
{% else %}
<p>Sorry, we could not finish your request.</p>
{% endif %}
{% endblock %}